version: "3.4"

services:
  newsapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      [
        "sh",
        "-c",
        "python manage.py rqworker --with-scheduler",
        "/docker_runserver.sh",
      ]
    volumes:
      - .:/code/
    networks:
      - webnet
    ports:
      - 9000:9000
    env_file:
      - ./config/.env
    depends_on:
      - db
      - redis

  db:
    container_name: postgres_db
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=postgres_dev
    networks:
      - webnet
    expose:
      - 5432

  redis:
    container_name: redis
    image: redis:6.0
    command: redis-server
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - webnet
    expose:
      - 6379
    

networks:
  webnet:

volumes:
  postgres_data:
  redis-data:
