# Generated by Django 3.1.1 on 2021-01-20 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=525, verbose_name='title')),
                ('link', models.URLField(max_length=255, verbose_name='link')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('upvotes', models.IntegerField(default=0, verbose_name='upvoutes')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='creation date')),
            ],
            options={
                'ordering': ['-creation_date', '-upvotes'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news_app.news', verbose_name='post')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
